<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CategoriesService.Application\CategoriesService.Application.csproj" />
    <ProjectReference Include="..\CategoriesService.Persistence\CategoriesService.Persistence.csproj" />
  </ItemGroup>

</Project>
